name: validate terraform

on:
  workflow_call:

permissions:
  id-token: write

jobs:
  sandbox:
    uses: iccowan/AviationAPIv2/.github/workflows/tf-plan.yml@main
    with:
      environment: sandbox

  staging:
    uses: iccowan/AviationAPIv2/.github/workflows/tf-plan.yml@main
    with:
      environment: staging

  prod:
    uses: iccowan/AviationAPIv2/.github/workflows/tf-plan.yml@main
    with:
      environment: prod
